version: '3.8'

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge

volumes:
  blog_db:
  blog_content:
  users_content:
  nginx_config:
  
services:
  
  db:
    image: postgres:16-ubuntu
    container_name: blog_postgresql_db
    environment:
      POSTGRES_DB: blogserver
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: blog
    volumes: 
      - blog_db:/var/lib/postgresql/data
    networks:
      - backend-network
    restart: always

  users:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog_scripts
    environment:
      POSTGRES_DB: blogserver
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: blog
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - users_content:/home/authors
      - blog_content:/var/www/blogs_public
    networks:
      - backend-network
      - frontend-network
    depends_on:
      - db
    entrypoint: /home/scripts/db_postgre.sh
    restart: always
  
  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - blog_nginx:/etc/nginx/conf.d/blogs.conf:ro
      - blog_content:/var/www/blogs_public
    networks:
     - frontend-network
    depends_on:
      - users
    restart: always
  
    
      
  